### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by Puntoboy** [lbschenkel/hass-addon-broadlink-bridge#2]
I'm getting this error when starting the addon. How do I fix it?

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2020-12-03 15:45:37,824 INFO     Starting broadlink-bridge/0.1.6...
2020-12-03 15:45:37,826 INFO     Reading config file: /config/custom_components/broadlink_bridge/config.ini
2020-12-03 15:45:37,827 INFO     Registering command: philips/power-off
2020-12-03 15:45:37,828 INFO     Registering command: denon/power-on
2020-12-03 15:45:37,829 INFO     Registering command: panasonic/power-on
Traceback (most recent call last):
  File "/usr/local/bin/broadlink-bridge", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/broadlink_bridge/cli.py", line 63, in main
    REGISTRY.add_manual_device(url, alias)
  File "/usr/local/lib/python3.9/site-packages/broadlink_bridge/__init__.py", line 18, in add_manual_device
    return self._add_device(host, alias)
  File "/usr/local/lib/python3.9/site-packages/broadlink_bridge/__init__.py", line 76, in _add_device
    dev = Device(dev)
  File "/usr/local/lib/python3.9/site-packages/broadlink_bridge/__init__.py", line 99, in __init__
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/broadlink_bridge/__init__.py", line 109, in connect
    connected = self._dev.auth()
  File "/usr/local/lib/python3.9/site-packages/broadlink/device.py", line 198, in auth
    check_error(response[0x22:0x24])
  File "/usr/local/lib/python3.9/site-packages/broadlink/exceptions.py", line 137, in check_error
    raise exception(error_code)
broadlink.exceptions.AuthenticationError: [Errno -1] Authentication failed
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.`

**Comment by lbschenkel** [comment]
What is your hardware? Virtually all the work is done by [python-broadlink](https://github.com/mjg59/python-broadlink). It can be a bug in there, or it can be a misuse of the library at my end. But it's very hard for me to diagnose and troubleshoot these kind of issues, because everything works fine with the hardware I have (RM3 Pro).

**Comment by Puntoboy** [comment]
I'm running HA/supervisor as a Virtual Machine on a Synology NAS. I'm thinking this is an authentication issue with the MQTT broker. But I have several other devices using it without a problem.

**Comment by lbschenkel** [comment]
I meant your Broadlink device. It wasn't a MQTT issue, the problem here is that there was an error inside `python-broadlink` while authenticating with your device.

**Comment by Puntoboy** [comment]
I haven’t got far enough to setup the broad link I think. I will check.

Kind regards,
Chris Jeffrey

Get Outlook<https://aka.ms/qtex0l> for iOS
________________________________

**Comment by lbschenkel** [comment]
I am closing this due to inactivity. In case there is more information available, feel free to reopen.
